create table game
(
    current_player_user_profile_id bigint                                 not null,
    current_turn_turn_id           bigint,
    game_id                        bigint generated by default as identity,
    winner_user_profile_id         bigint,
    state                          enum ('FINISHED','IN_PLAY','PRE_GAME') not null,
    primary key (game_id)
);
create table roll
(
    farkle     boolean,
    roll_score integer,
    roll_id    bigint generated by default as identity,
    primary key (roll_id)
);
create table roll_dice_values
(
    dice_values  integer,
    roll_roll_id bigint not null
);
create table roll_number_dice
(
    number_dice  integer,
    roll_roll_id bigint not null
);
create table score_master
(
    bank_score integer,
    score_id   bigint generated by default as identity,
    primary key (score_id)
);
create table score_master_dice_values
(
    dice_values           integer,
    score_master_score_id bigint not null
);
create table turn
(
    finished   boolean not null,
    turn_score integer not null,
    game_id    bigint  not null,
    turn_id    bigint generated by default as identity,
    primary key (turn_id)
);
create table user_profile
(
    user_profile_id bigint generated by default as identity,
    external_key    uuid not null unique,
    auth_key        varchar(255),
    display_name    varchar(255),
    primary key (user_profile_id)
);
alter table if exists game
    add constraint FK65l7adprmfq4ll4q371i1admw foreign key (current_player_user_profile_id) references user_profile;
alter table if exists game
    add constraint FKa91aompdbsmkdlqltkmq68ga0 foreign key (current_turn_turn_id) references turn;
alter table if exists game
    add constraint FKp7oy6bephetwdo1a8uwwkmoc foreign key (winner_user_profile_id) references user_profile;
alter table if exists roll_dice_values
    add constraint FKboapqksmjr13ieyp2d9s9folh foreign key (roll_roll_id) references roll;
alter table if exists roll_number_dice
    add constraint FK4gpi2qt1tlt315549ny3f4uwr foreign key (roll_roll_id) references roll;
alter table if exists score_master_dice_values
    add constraint FK21wxamqdwmi5lnsyt6cathxm9 foreign key (score_master_score_id) references score_master;
alter table if exists turn
    add constraint FKfnda1g6jd92jpiakpu2689pgf foreign key (game_id) references game;
