name: Graph Generation

on:
  push:
    branches:
      - mincfranc-patch-1

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install graphviz

      - name: Generate Graph
        run: |
          python Infrastructure/generate_graph.py  # Run the script

      - name: Commit and push the generated graph
        run: |
          git add Infrastructure/rubric_graph.svg
          git commit -m "Add generated rubric graph"
          git push
